### ISSUE TITLE
SPIKE: investigate testing REST service and choose the best way to test it

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/CarSale#12]
As a developer, I need to test the REST service.

Questions for investigation:
   1. What are the ways to test REST services
   2. What can we test by these ways 
   3. Which way of testing is the best for the current application
   4. Why is it the best way

Estimation time: 2 hours

**Comment by maksimk99** [comment]
There are some ways to test REST services:
  - MockMVC
  - RestTemplate
  - WireMock
  - MockRestServiceServer

MockMVC is used for testing REST on the server side, it can be used both for unit tests and for integration tests.
RestTemplate is used for testing REST on the client side but also can be used for integration tests on the server side.
WireMock is used to simulate a web server on the client side.
MockRestServiceServer is used to mock restTemplate on the client side.

RestTemplate is not a good decision to make integration tests on the server side because it deploys an actual server instance to listen for the HTTP requests you send.

In my opinion, MockMVC is the best choice to test REST controllers in the current application

**Comment by aleksieiev** [comment]
Agreed
