### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/CarSale#22]
1. create custom exceptions to easily validate exception
2. exception handling to set response status on rest controllers

estimation time: 8 hours

**Comment by maksimk99** [comment]
I need to add more information to the exception response object

**Comment by aleksieiev** [comment]
What kind of information?
How Exception should looks like?
What is the strategy of implementation?

**Comment by maksimk99** [comment]
I will add date when the exception was thrown and status code

**Comment by aleksieiev** [comment]
not enough

**Comment by maksimk99** [comment]
It is Spring Boot response:


    "timestamp": "2019-01-17T16:12:45.977+0000",
    "status": 500,  
    "error": "Internal Server Error",  
    "message": "Error processing the request!",  
    "path": "/my-endpoint-with-exceptions"  
I missed only error field because I think it is redundant for my case

**Comment by aleksieiev** [comment]
1. wrong format
2. Currently project doesn't have Spring Boot support.
3. I even can't imagine what field has been missed because I neither see current exception message example nor any **bold** or _italic_  in the message above. Unfortunately, my crystal ball of foresight doesn't work today.

**Comment by maksimk99** [comment]
My response:

    "date":1569400372186,
    "status":404,
    "message":"there is not car sale with id = 133",
    "url":"http://localhost:8080/carSale/133"

**Comment by aleksieiev** [comment]
1. wrong format
2. wrong date format
3. wrong URL format.

**Comment by maksimk99** [comment]
I didn't understand what does your first paragraph mean but two other I changed

    "date":"25-09-2019 08:59:21",
    "status":404,
    "message":"there is not car sale with id = 123",
    "path":"/carSale/123"

**Comment by aleksieiev** [comment]
OK. Implement this and provide me here screenshots of your exception

**Comment by maksimk99** [comment]
![Screenshot from 2019-09-25 13-15-22](https://user-images.githubusercontent.com/47476838/65592651-a9014800-df97-11e9-833c-8267f443573f.png)

**Comment by maksimk99** [comment]
Did you mean this?

**Comment by aleksieiev** [comment]
Yes.
Copy and paste real answer from the service and align it.

**Comment by maksimk99** [comment]
{
     "date":"25-09-2019 08:59:21",
     "status":404,
     "message":"there is not car sale with id = 123",
     "path":"/carSale/123"
    }

**Comment by aleksieiev** [comment]
How do you think is it the same like above or not? Did it meet expectations?

**Comment by maksimk99** [comment]
I added brackets and I think it is correct.
now it looks like in the example from the tutorial

**Comment by aleksieiev** [comment]
1. I don't know what tutorial are you talking about
2. I even don't want to know
3. I found that you proposed format w/o brackets. As a customer I accepted it. So, implement exactly that case, prepare PR and add screenshot with full description how to reproduce the same result.

**Comment by maksimk99** [comment]
I've changed error response type to JSON and created pull request which is merged now
