### ISSUE TITLE
SPIKE: investigate Swagger.

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/CarSale#25]
As a developer I want to have clear API description and possibility to check API changes.
Please investigate is it possible to add Swagger or any other tool for API documentation.
As a result I expect estimation time for develop this feature and any important details.

**Comment by maksimk99** [comment]
I investigated Swagger and as I discovered Swagger can be added for API documentation
Estimation time to enable Swagger in the project is 1 hour
Estimation time to add annotations(comments) on controllers (It will make API documentation more understandable)  is 4 hour

**Comment by aleksieiev** [comment]
From your point of view, which one from these solutions is more preferable?

**Comment by maksimk99** [comment]
I think the second solution is better because I can describe what is a method used for, some important notice and custom exception

**Comment by aleksieiev** [comment]
ok.
create task for it and follow standard process
