### ISSUE TITLE
add functionality to filter data

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/CarSale#30]
1. add an endpoint which returns a list of car sale dto
2. add functionality to return car sale list according to parameters passed to the controller 
estimation time 4 hours

**Comment by aleksieiev** [comment]
what kind of parameters should be supported?
what endpoint will be created?

**Comment by maksimk99** [comment]
It supports the next parameters:
_**CarMakeId, CarModelId, YearFrom, YearTo, PriceFrom, PriceTo.**_  

### Get list car sales with conditions endpoint:
**Resource url:** /carSale
**Parameters:** 
  _carMakeId: type = int, example = 1
  carModelId: type = int, example = 1
  yearFrom: type = date, example = 2014-01-01
  yearTo: type = date, example = 2018-01-01
  priceFrom: type = int, example = 20000
  priceTo: type = int, example = 40000_
**Response format:** JSON  
**Response status:** 200 
  
**Example request:** `GET /carSale?carMakeId=1&carModelId=1&yearFrom=2014-01-01&yearTo=2018-01-01&priceFrom=20000&priceTo=40000`

**Example response body:**
``` 
[{"carSaleId":1,"price":36800,"date":1559336400000,"year":1483218000000,"mileage":90300,
"fuelType":"Bensin","transmission":"Automatic","carMake":"Mercedes","carModel":"C63_AMG"}, 
 {"carSaleId":3,"price":26800,"date":1560200400000,"year":1420059600000,"mileage":130300,
"fuelType":"Diesel","transmission":"Automatic","carMake":"Mercedes","carModel":"C63_AMG"}]
```

**Comment by aleksieiev** [comment]
Which ones are mandatory?

**Comment by maksimk99** [comment]
they are all optional
