### ISSUE TITLE
create complex request to database

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/CarSale#37]
As a developer, I decided to make a more complex request to the database to reduce the count of calling database
I need to get from the database object which contains lists of objects as fields, to do this I convert data to JSON in SQL query and then convert it to object using ObjectMapper

**Comment by aleksieiev** [comment]
Estimations?
How many requests will be with a new approach?
Response data structure?

**Comment by maksimk99** [comment]
with a new approach, there will be only one request which returns an object which contains list car makes, fuel types, transmissions, and car features.
The response will be in JSON format:
```
{
  "carMakeList": [
    {
      "carMake": "Mercedes",
      "carMakeId": 1
    },
    {
      "carMake": "BMW",
      "carMakeId": 2
    }
  ],
  "fuelTypeList": [
    {
      "fuelType": "Bensin",
      "fuelTypeId": 1
    },
    {
      "fuelType": "Diesel",
      "fuelTypeId": 2
    }
  ],
  "carFeatureList": [
    {
      "carFeature": "Winter tires",
      "carFeatureId": 1
    },
    {
      "carFeature": "air conditioning",
      "carFeatureId": 2
    }
  ],
  "transmissionList": [
    {
      "transmission": "Automatic",
      "transmissionId": 1
    },
    {
      "transmission": "Manual",
      "transmissionId": 2
    }
  ]
}
```

**Comment by maksimk99** [comment]
already merged
