### ISSUE TITLE
Add DB entities diagram

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/CarSale#4]
Add DB entities diagram in project documentation.
Also model hierarchy and connections between them.

**Comment by maksimk99** [comment]
I've added with a new commit to the exsistent pull request

**Comment by aleksieiev** [comment]
Are you really?
Why it has been added as commit to the existing PR if it should be separate PR?
Are you sure that you understand me correctly last time???

**Comment by maksimk99** [comment]
check it out

**Comment by maksimk99** [comment]
merged
