### ISSUE TITLE
Add endpoints to get single comment by id and list comments with car sale advertisement

### ISSUE THREAD

**Issue by maksimk99** [java-fat-unicorn-team/CarSale#41]
I need to add one edition endpoint to get one comment by id(it is used for update method on the client-side) and add a comment list field to the car sale object(it is used to get car sale advertisement and comments of this advertisement in one request)

**Comment by aleksieiev** [comment]
1. Bad name of the issue.
Think "Add comments endpoints for adding single comment to the advertisement" will be better.
2. This issue also can be separated for 2 independent.

Try to rename the issue for understanding what should been done in it.
