### ISSUE TITLE
SPIKE: investigate REST service contract and endpoints

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/CarSale#8]
As a developer I need to develop REST endpoints for current business model. It should contains possibility for all CRUD operations.

Questions for investigations:
1. Which entities should have REST endpoints.
2. Names of endpoints for entities
3. REST methods for each endpoint.
4. Mandatory/optional parameters list.

@maksimk99 please estimate this issue.

**Comment by maksimk99** [comment]
I will spend about 2 days on it

**Comment by maksimk99** [comment]
merged

**Comment by aleksieiev** [comment]
How can I find what exactly has been merged? Neither PR nor merge commit has been provided.
