### ISSUE TITLE
Refactor application to multimodule project

### ISSUE THREAD

**Issue by aleksieiev** [java-fat-unicorn-team/CarSale#9]
Current application should be refactored to multimodule Maven project.
I see at least 2 subprojects:
1. model
2. DAO layer

From my point of view it gives us an opportunity to reuse modules somewhere else (but we won't do this :-) ).

@maksimk99 please estimate it and implement.

**Comment by maksimk99** [comment]
Sorry, I've forgotten to estimate it,
I've already refactored an application.

**Comment by maksimk99** [comment]
merged

**Comment by aleksieiev** [comment]
always provide some links to commits or pull request according to the task
